remote_theme: pages-themes/hacker
title: Void's Archive
author:
  name: 
  email: 
description: > # this means to ignore newlines until "show_excerpts:"
  Reviews of various video games Void has played, beaten, or completed. An extension of their Backloggery.
normalize: true
darkmode: true