remote_theme: moonharelabs/styless
title: Void's Archive
author:
  name: 
  email: 
description: > # this means to ignore newlines until "show_excerpts:"
  I could say something edgy about the void here. 
  Instead, I'll remind you to surround yourself with
  things that make you happy, rather than surrouding
  yourself with things that make you feel dread.
normalize: true
darkmode: true