# remote_theme: moonharelabs/styless
# title: Void's Archive
# author:
#  name: 
#  email: 
# description: > # this means to ignore newlines until "show_excerpts:"
#  I could say something edgy about the void here. 
#  Instead, I'll remind you to surround yourself with
#  things that make you happy, rather than surrouding
#  yourself with things that make you feel dread.
# normalize: true
# darkmode: true

remote_theme: b2a3e8/jekyll-theme-console
header_pages:
  - index.md
  - about.md

style: dark # dark (default), light or hacker
listen_for_clients_preferred_style: true # false (default) or true

# footer: 'follow us on <a href="https://twitter.com/xxx">twitter</a>'