remote_theme: moonharelabs/styless
title: Voi'd Archive
author:
  name: 
  email: 
description: > # this means to ignore newlines until "show_excerpts:"
  A super cool description would go here if it really mattered.
normalize: true
darkmode: true